### ISSUE TITLE
Not a time-based UUID

### ISSUE THREAD

**Issue by Kolesar** [gbprod/uuid-normalizer#11]
After installing `uuid-normalizer`, I still have error `Not a time-based UUID`.

This is the packages what I installed:
```
"gbprod/uuid-normalizer": "~1.2.0",
"ramsey/uuid-doctrine": "~1.6.0",
```

And simple Controller looks like:
```
        $nomalizers = [
            new ObjectNormalizer(),
        ];

        $endocers = [
            new JsonEncoder(),
        ];

        $serializer = new Serializer($nomalizers, $endocers);
        $serializedData = $serializer->serialize($user, 'json');
```

User Entity has this for UUID:
```
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @Assert\Uuid
     * @var UuidInterface
     */
    private $uuid;

    public function __construct()
    {
        $this->uuid = Uuid::uuid4();
    }
```

I'm pretty sure, I missed something, but I do not know what :/ Can you help me with this, please?

P.S.
I cannot use the following for the `uuid` field, because I have to migrate data from the old DB, and have to be able to set `uuid` manually by setters, not only by `UUIDGenerator`:
```
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @Assert\Uuid
     * @var UuidInterface
     */
    private $uuid;
```

**Comment by gbprod** [comment]
You have to construct your `Serializer` with `UuidNormalizer` and `UuidDenormalizer` :

   use​ ​GBProd​\​UuidNormalizer​\​UuidDenormalizer​;
    ​use​ ​GBProd​\​UuidNormalizer​\​UuidNormalizer​;

    ...

    $nomalizers = [
        new ObjectNormalizer(),
        new​ ​UuidNormalizer​(),
        new ​UuidDenormalizer​(),
    ];
